{{- if .Values.autoscaling.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "test-devops.fullname" . }}
  labels:
    {{- include "test-devops.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "test-devops.fullname" . }}
  updatePolicy:
    updateMode: "Off"
{{- end }}
